version: 2
jobs:
  build:
    docker:
      - image: golang
    working_directory: /go/src/github.com/raviqqe/muffet
    steps:
      - checkout

      - run:
          name: Lint
          command: |
            go get -u github.com/alecthomas/gometalinter
            gometalinter --install
            gometalinter ./...

      - run:
          name: Build
          command: go build

      - run:
          name: Test
          command: go test
