version: 2
jobs:
  build:
    docker:
      - image: golang
    working_directory: /go/src/github.com/raviqqe/muffet
    steps:
      - checkout

      - run:
          name: Setup
          command: |
            apt -y update --fix-missing
            apt -y upgrade
            apt -y install python3 rake

      - run:
          name: Dependencies
          command: rake deps

      - run:
          name: Lint
          command: rake lint

      - run:
          name: Build
          command: rake build

      - run:
          name: Unit Test
          command: rake unit_test

      - run:
          name: Integration Test
          command: |
            rake serve
            rake integration_test
