version: 2
jobs:
  build:
    docker:
      - image: golang
    working_directory: /go/src/github.com/raviqqe/muffet
    steps:
      - checkout

      - run:
          name: Dependencies
          command: |
            go get -u github.com/alecthomas/gometalinter
            go get -d -t ./...

      - run:
          name: Lint
          command: |
            gometalinter --install
            gometalinter --disable vetshadow ./...

      - run:
          name: Build
          command: go build

      - run:
          name: Unit Test
          command: go test

      - run:
          name: Integration Test
          command: |
            ./muffet https://coel-lang.org
            ./muffet https://raviqqe.com
            ! ./muffet https://www.hackthissite.org
            ./muffet -c 1 https://coel-lang.org
            ./muffet --concurrency 1 https://coel-lang.org
            ./muffet -c 1 https://raviqqe.com
            ./muffet --concurrency 1 https://raviqqe.com
            ./muffet --help
            ./muffet -v https://raviqqe.com 2>&1 | grep OK
            ./muffet --verbose https://raviqqe.com 2>&1 | grep OK
            ! ./muffet https://raviqqe.com 2>&1 | grep OK
            ./muffet -v https://coel-lang.org 2>&1 | sort > foo.txt
            ./muffet -v https://coel-lang.org 2>&1 | sort > bar.txt
            diff foo.txt bar.txt
